export const FETCH_FEATURED_PROGRAMS = 'FETCH_FEATURED_PROGRAMS';
export const SET_AVAILABLE_PROGRAMS = 'SET_AVAILABLE_PROGRAMS';
export const SET_CURRENT_PROGRAM = 'SET_CURRENT_PROGRAM';
export const ERROR_FETCHING_PROGRAMS = 'ERROR_FETCHING_PROGRAMS';
